IdentifyProject/Controllers/IdentifyHomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace IdentifyProject.Controllers
{
    public class IdentifyHomeController : Controller
    {
        // GET: IdentifyHome
        public ActionResult Index()
        {
            return View();
        }
    }
}

IdentifyProject/Views/IdentifyHome/Index.cshtml
<!DOCTYPE html>
@{
    Layout = null;
}


<html lang="zxx" class="no-js">
<head>
    <!-- Mobile Specific Meta -->
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <!-- Favicon-->
    <link rel="shortcut icon" href="~/Content/img/fav.png">

    <!-- Author Meta -->
    <meta name="author" content="Colorlib">
    <!-- Meta Description -->
    <meta name="description" content="">
    <!-- Meta Keyword -->
    <meta name="keywords" content="">
    <!-- meta character set -->
    <meta charset="UTF-8">
    <!-- Site Title -->
    <title>Identify-Let's Reunite</title>

    <link href="https://fonts.googleapis.com/css?family=Poppins:100,200,400,300,500,600,700" rel="stylesheet">

    <!--
    CSS
    ============================================= -->

    <link href="~/Content/css/linearicons.css" rel="stylesheet" />
    <link rel="stylesheet" href="~/Content/css/font-awesome.min.css">
    <link rel="stylesheet" href="~/Content/css/magnific-popup.css">
    <link rel="stylesheet" href="~/Content/css/nice-select.css">
    <link rel="stylesheet" href="https://code.jquery.com/ui/1.12.1/themes/base/jquery-ui.css">
    <link rel="stylesheet" href="~/Content/css/bootstrap.css">
    <link rel="stylesheet" href="~/Content/css/mains.css">
    <style>
        body {
            font-family: Arial, Helvetica, sans-serif;
        }

        /* The Modal (background) */
        .modal {
            display: none; /* Hidden by default */
            position: fixed; /* Stay in place */
            z-index: 1; /* Sit on top */
            padding-top: 100px; /* Location of the box */
            left: 0;
            top: 0;
            width: 100%; /* Full width */
            height: 100%; /* Full height */
            overflow: auto; /* Enable scroll if needed */
            background-color: rgb(0,0,0); /* Fallback color */
            background-color: rgba(0,0,0,0.4); /* Black w/ opacity */
        }

        /* Modal Content */
        .modal-content {
            background-color: #fefefe;
            margin: auto;
            padding: 20px;
            border: 1px solid #888;
            width: 50%;
        }

        /* The Close Button */
        .close {
            color: #aaaaaa;
            float: right;
            font-size: 28px;
            font-weight: bold;
        }

            .close:hover,
            .close:focus {
                color: #000;
                text-decoration: none;
                cursor: pointer;
            }
    </style>
</head>
<body>

    <!-- Start Header Area -->
    <header class="default-header">
        <div class="container">
            <div class="header-wrap">
                <div class="header-top d-flex justify-content-between align-items-center">
                    <div class="logo">
                        <a href="#home"><img src="~/Content/img/logox.png" /></a>
                    </div>
                    <div class="main-menubar d-flex align-items-center">
                        <nav class="hide">
                            @Html.ActionLink("Home", "Index", "IdentifyHome")
                            @Html.ActionLink("Sighted", "Index", "Sigthed")
                            @Html.ActionLink("Missing", "Index", "Missing")
                            <a href="http://localhost:28883/Faces/Detect">Facial Recognition</a>
                            
                            @Html.ActionLink("Login", "Login", "Account")
                        </nav>

                        <div class="menu-bar"><span class="lnr lnr-menu"></span></div>
                    </div>
                </div>
            </div>
        </div>
    </header>
    <!-- End Header Area -->
    <!-- start banner Area -->
    <section class="banner-area relative" id="home">
        <div class="overlay overlay-bg"></div>
        <div class="container">
            <div class="row fullscreen align-items-center justify-content-start" style="height: 915px;">
                <div class="banner-content col-lg-8 col-md-12">
                    <h1>
                        Be a HERO to the missing one's,
                        help them reunite with their loved ones.
                    </h1>
                    @Html.ActionLink("Register", "Register", new { controller = "Account" }, new { @class = "head-btn btn text-uppercase" })

                </div>
            </div>
        </div>
    </section>
    <!-- End banner Area -->
    <!-- Start project Area -->
    <section class="project-area section-gap" id="project">
        <div class="container">

            <div class="row d-flex justify-content-center">
                <div class="col-md-12 pb-80 header-text">

                    <h2> Shocking Stats!</h2>
                    <br />

                    <h3>
                        <p>
                            A deeply disturbing fact about India’s missing children is that while on an average 174 children go missing every day, half of them remain untraced. 
                            <hr />
                            “Most of the missing children are trafficked for labour, for sexual exploitation, abducted, or kidnapped ... They could be runaways from home, or simply be lost," said a government statement.

                        </p>
                    </h3>

                    <hr />
                    <h3>
                        <p>
                            [Won't you spare a few minutes to change someone's life?]
                        </p>
                    </h3>
                </div>

            </div>
            <div class="row">
                <div class="col-lg-4 col-md-4 project-wrap">
                    <div class="single-project">
                        <div class="content">
                            <a href="#" target="_blank">

                                <div class="content-overlay"></div>
                                <img class="content-image img-fluid d-block mx-auto" src="~/Content/img/p1.jpg" alt="lost">
                                <div class="content-details fadeIn-bottom">
                                    @Html.ActionLink("Fill In Details", "Index", new { controller = "Missing" }, new { @class = "head-btn btn text-uppercase" })

                                </div>
                            </a>
                        </div>
                    </div>
                    <div class="details">
                        <center>
                            <h2>I Lost/Sighted </h2>
                            <p>Did you lost or sighted someone? Fill in the details of the child/person who's been missing or sighted.</p>
                        </center>
                    </div>

                </div>
                <div class="col-lg-4 col-md-4 project-wrap">
                    <div class="single-project">
                        <div class="content">

                            <div class="content-overlay"></div>
                            <img class="content-image img-fluid d-block mx-auto" src="~/Content/img/p2.jpg" alt="">
                            <div class="content-details fadeIn-bottom">
                                <a href="https://uidai.gov.in/ecosystem/authentication-devices-documents/biometric-devices.html" class="head-btn btn text-uppercase">Scan</a>
                            </div>
                            </a>
                        </div>
                    </div>
                    <div class="details">
                        <center>
                            <h2>Biometric Search</h2>
                            <h6>(Access Granted: Police Officials)</h6> 
                            <p>Identify by just scanning the fingerprint of the child/person.</p>
                        </center>
                    </div>
                </div>
                <div class="col-lg-4 col-md-4 project-wrap">
                    <div class="single-project">
                        <div class="content">
                            <a href="#" target="_blank">
                                <div class="content-overlay"></div>
                                <img class="content-image img-fluid d-block mx-auto" src="~/Content/img/p3.jpg" alt="">
                                <div class="content-details fadeIn-bottom">
                                    <a href="http://localhost:28883/Faces/Detect" class="head-btn btn text-uppercase">Facial Recognition</a>
                                </div>
                            </a>
                        </div>
                    </div>
                    <div class="details">
                        <center>
                            <h2>Face Identify</h2>
                            <p>Use the smart facial recognition technology to search your loved ones who's missing.</p>
                        </center>
                    </div>
                </div>

            </div>
        </div>
    </section>
    <!-- End project Area -->
    <!-- Start about Area -->
    <section class="about-area" id="about">
        <div class="container-fluid">
            <div class="row d-flex justify-content-end align-items-center">
                <div class="col-lg-6 col-md-12 about-left no-padding">
                    <img class="img-fluid" src="~/Content/img/about-img.jpg" alt="">
                </div>
                <div class="col-lg-6 col-md-12 about-right">
                    <h1>Let's Reunite</h1>

                    <p>
                        Identify is a web application, which allows you to share the picture and details of people you see on road side, and feel they are lost. The site will connect to databases and use facial recognition to find a probable match, allowing him/her to see the whereabouts of the child.
                        Files of FIRs are filled with such cases, however best possible way to get them back to their home is using the technologies to make them meet their families. Even if we can do it for one of them, our purpose is solved.
                    </p>
                    <button id="myBtn" class="primary-btn mt-20 text-uppercase ">Donate <span class="lnr lnr-arrow-right"></span></button>
                </div>
            </div>
        </div>
    </section>

    <!-- End about Area -->
    <!-- The Modal -->
    <div id="myModal" class="modal">

        <!-- Modal content -->
        <div class="modal-content">
            <span class="close">&times;</span>
            <center>
                <h3>Donate Now</h3>
                <br />
                <p>
                    Help us keep this awesome website alive, Scan it in your Paytm app to donate.<br />
                    <br /><img src="~/Content/img/QR-code-example.jpg" width="200px" />
                </p>
            </center>
        </div>
    </div>
    <!-- start footer Area -->
    <footer class="footer-area section-gap">
        <div class="container">
            <div class="row d-flex flex-column justify-content-center">

                <div class="footer-social">
                    <a href="#"><i class="fa fa-facebook"></i></a>
                    <a href="#"><i class="fa fa-twitter"></i></a>
                    <a href="#"><i class="fa fa-dribbble"></i></a>
                    <a href="#"><i class="fa fa-behance"></i></a>
                </div>
                <p class="footer-text m-0">
                    <!-- Link back to Colorlib can't be removed. Template is licensed under CC BY 3.0. -->
                    Copyright &copy;
                    <script>document.write(new Date().getFullYear());</script> All rights reserved | This website is made with <i class="fa fa-heart-o" aria-hidden="true"></i> by <a href="https://www.instagram.com/md.mudassir7/" target="_blank">Elite Hackers</a>
                    <!-- Link back to Colorlib can't be removed. Template is licensed under CC BY 3.0. -->
                </p>
            </div>
        </div>
    </footer>
    <!-- End footer Area -->

    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.11.0/umd/popper.min.js" integrity="sha384-b/U6ypiBEHpOf/4+1nzFpr53nxSS+GLCkfwBdFNTxtclqqenISfwAzpKaMNFNmj4" crossorigin="anonymous"></script>


    <script src="~/Content/js/vendor/bootstrap.min.js"></script>
    <script src="~/Content/js/vendor/jquery-2.2.4.min.js"></script>
    <script src="~/Content/js/jquery.ajaxchimp.min.js"></script>
    <script src="~/Content/js/jquery.nice-select.min.js"></script>
    <script src="~/Content/js/jquery.sticky.js"></script>
    <script src="~/Content/js/parallax.min.js"></script>
    <script src="https://code.jquery.com/ui/1.12.1/jquery-ui.js"></script>
    <script src="~/Content/js/jquery.magnific-popup.min.js"></script>
    <script src="~/Content/js/main.js"></script>
    <script>
// Get the modal
var modal = document.getElementById('myModal');

// Get the button that opens the modal
var btn = document.getElementById("myBtn");

// Get the <span> element that closes the modal
var span = document.getElementsByClassName("close")[0];

// When the user clicks the button, open the modal
btn.onclick = function() {
  modal.style.display = "block";
}

// When the user clicks on <span> (x), close the modal
span.onclick = function() {
  modal.style.display = "none";
}

// When the user clicks anywhere outside of the modal, close it
window.onclick = function(event) {
  if (event.target == modal) {
    modal.style.display = "none";
  }
}
    </script>

</body>
</html>