CognitiveServicesDemo/CognitiveServicesDemo/Areas/Faces/Controllers/PersonGroupsController.cs
using System;
using System.Threading.Tasks;
using System.Web.Mvc;
using CognitiveServicesDemo.Areas.Faces.Models;
using Microsoft.ProjectOxford.Face;
using Microsoft.ProjectOxford.Face.Contract;

namespace CognitiveServicesDemo.Areas.Faces.Controllers
{
    public class PersonGroupsController : FacesBaseController
    {
        public async Task<ActionResult> Index()
        {
            var groups = await FaceClient.ListPersonGroupsAsync();

            return View(groups);
        }

        public async Task<ActionResult> Details(string id)
        {
            if(string.IsNullOrEmpty(id))
            {

            }

            var model = new PersonGroupDetailsModel();
            model.PersonGroup = await FaceClient.GetPersonGroupAsync(id);

            try
            {
                model.TrainingStatus = await FaceClient.GetPersonGroupTrainingStatusAsync(id);
            }
            catch (FaceAPIException fex)
            {
                ModelState.AddModelError(string.Empty, fex.ErrorMessage);
            }

            return View(model);
        }

        [HttpGet]
        public ActionResult Create()
        {
            return View(new PersonGroup());
        }

        [HttpPost]
        public async Task<ActionResult> Create(PersonGroup model)
        {
            try
            {
                await FaceClient.CreatePersonGroupAsync(model.PersonGroupId, model.Name, model.UserData);
            }
            catch (FaceAPIException fex)
            {
                ModelState.AddModelError(string.Empty, fex.ErrorMessage);
                return View(model);
            }
            catch (Exception ex)
            {
                ModelState.AddModelError(string.Empty, ex.Message);
                return View(model);
            }

            return RedirectToAction("Index");
        }

        [HttpGet]
        public async Task<ActionResult> Edit(string id)
        {
            var model = await FaceClient.GetPersonGroupAsync(id);

            return View(model);
        }

        [HttpPost]
        public async Task<ActionResult> Edit(PersonGroup model)
        {
            await FaceClient.UpdatePersonGroupAsync(model.PersonGroupId, model.Name, model.UserData);

            return RedirectToAction("Index");
        }

        public async Task<ActionResult> Train(string id)
        {
            await FaceClient.TrainPersonGroupAsync(id);

            return RedirectToAction("Details", new { id = id });
        }
        
        [HttpGet]
        public async Task<ActionResult> Delete(string id)
        {
            await FaceClient.DeletePersonGroupAsync(id);
            return RedirectToAction("Index", new { id = id });
        }
    }
}

CognitiveServicesDemo/CognitiveServicesDemo/Areas/Faces/Views/PersonGroups/Create.cshtml
@model PersonGroup
@{
    ViewBag.Title = "Create person group";
}

<h2>Create person group</h2>

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <hr />
        @Html.ValidationSummary(false, null, new { @class = "text-danger" })

        <div class="form-group">
            @Html.LabelFor(model => model.PersonGroupId, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.PersonGroupId, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.PersonGroupId, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Name, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.UserData, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.TextAreaFor(model => model.UserData, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.UserData, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "PersonGroups")
</div>

CognitiveServicesDemo/CognitiveServicesDemo/Areas/Faces/Views/PersonGroups/Details.cshtml
@model PersonGroupDetailsModel
@{
    ViewBag.Title = "Person group " + Model.PersonGroup.Name;
}

<h2>Person group details</h2>

<div>
    @Html.ValidationSummary(false, null, new { @class = "text-danger" })
    <hr />
    <dl class="dl-horizontal">

        <dt>
            @Html.DisplayNameFor(model => model.PersonGroup.PersonGroupId)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.PersonGroup.PersonGroupId)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.PersonGroup.Name)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.PersonGroup.Name)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.PersonGroup.UserData)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.PersonGroup.UserData)
        </dd>
        <hr />
        @if (Model.TrainingStatus == null)
        {
            <dt>
                TrainingStatus
            </dt>
                    <dd>
                        None
                    </dd>
        }
        else
        {
            <dt>
                TrainingStatus
            </dt>
                    <dd>
                        @Model.TrainingStatus.Status
                    </dd>

                    <dt>
                        Created
                    </dt>
                    <dd>
                        @Model.TrainingStatus.CreatedDateTime
                    </dd>

                    <dt>
                        Last actitivity
                    </dt>
                    <dd>
                        @Model.TrainingStatus.LastActionDateTime
                    </dd>

                    <dt>
                        Message
                    </dt>
                    <dd>
                        @Model.TrainingStatus.Message
                    </dd>
        }

    </dl>
</div>
<p>
    @Html.ActionLink("Back to List", "Index")
</p>

CognitiveServicesDemo/CognitiveServicesDemo/Areas/Faces/Views/PersonGroups/Edit.cshtml
@model PersonGroup
@{
    ViewBag.Title = "Edit person group";
}

<h2>Create person group</h2>

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <hr />
        @Html.ValidationSummary(false, null, new { @class = "text-danger" })
        @Html.HiddenFor(m => m.PersonGroupId)

        <div class="form-group">
            @Html.LabelFor(model => model.Name, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.UserData, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.TextAreaFor(model => model.UserData, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.UserData, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "PersonGroups")
</div>

CognitiveServicesDemo/CognitiveServicesDemo/Areas/Faces/Views/PersonGroups/Index.cshtml
@model IEnumerable<PersonGroup>
@{
    ViewBag.Title = "Person groups";
}

<h2>Person groups</h2>

<p>
    @Html.ActionLink("Create New", "Create")
</p>

<table class="table">
    <tr>
        <th>ID</th>
        <th>Name</th>
        <th></th>
    </tr>

    @foreach (var item in Model)
            {
        <tr>
            <td>@item.PersonGroupId</td>
            <td>@item.Name</td>
            <td>
                @Html.ActionLink("Details", "Details", new { id = item.PersonGroupId }) |
                @Html.ActionLink("Edit", "Edit", new { id = item.PersonGroupId }) |
                @Html.ActionLink("Train", "Train", new { id = item.PersonGroupId }) |
                @Html.ActionLink("People", "Index", "People", new { id = item.PersonGroupId }, new { }) |
                @Html.ActionLink("Delete", "Delete", new { id = item.PersonGroupId })
            </td>
        </tr>
    }
</table>