CognitiveServicesDemo/CognitiveServicesDemo/Areas/Faces/Controllers/PeopleController.cs
using System;
using System.IO;
using System.Threading.Tasks;
using System.Web.Mvc;
using Microsoft.ProjectOxford.Face;
using Microsoft.ProjectOxford.Face.Contract;

namespace CognitiveServicesDemo.Areas.Faces.Controllers
{
    public class PeopleController : FacesBaseController
    {
        public async Task<ActionResult> Index(string id)
        {
            if(string.IsNullOrEmpty(id))
            {
                return HttpNotFound("Person group ID is missing");
            }

            var model = await FaceClient.ListPersonsAsync(id);
            ViewBag.PersonGroupId = id;

            return View(model);
        }

        public async Task<ActionResult> Details(string id, Guid? personId)
        {
            if(string.IsNullOrEmpty(id))
            {
                return HttpNotFound();
            }

            if(personId == null)
            {
                return HttpNotFound();
            }

            var model = await FaceClient.GetPersonAsync(id, personId.Value);
            ViewBag.PersonGroupId = id;

            return View(model);
        }

        public ActionResult Create(string id)
        {
            ViewBag.PersonGroupId = id;

            return View("Edit", new Person());
        }

        [HttpPost]
        public async Task<ActionResult> Create(Person person)
        {
            return await Edit(person);
        }

        public async Task<ActionResult> Edit(string id, Guid personId)
        {
            ViewBag.PersonGroupId = id;

            var model = await FaceClient.GetPersonAsync(id, personId);

            return View(model);
        }

        [HttpPost]
        public async Task<ActionResult> Edit(Person person)
        {
            var personGroupId = Request.Form["PersonGroupId"];
            if(string.IsNullOrEmpty(personGroupId))
            {
                return HttpNotFound("PersonGroupId is missing");
            }

            if(!ModelState.IsValid)
            {
                ViewBag.PersonGroupId = personGroupId;
                return View(person);
            }

            try
            {
                if (person.PersonId == Guid.Empty)
                {
                    await FaceClient.CreatePersonAsync(personGroupId, person.Name, person.UserData);
                }
                else
                {
                    await FaceClient.UpdatePersonAsync(personGroupId, person.PersonId, person.Name, person.UserData);
                }

                return RedirectToAction("Index", new { id = personGroupId });
            }
            catch (FaceAPIException fex)
            {
                ModelState.AddModelError(string.Empty, fex.ErrorMessage);
            }

            return View(person);
        }

        [HttpGet]
        public ActionResult AddFace(string id, string personId)
        {
            return View();
        }

        [HttpPost]
        public async Task<ActionResult> AddFace()
        {
            var id = Request["id"];
            var personId = Guid.Parse(Request["personId"]);

            try
            {
                Request.Files[0].InputStream.Seek(0,SeekOrigin.Begin);
                await FaceClient.AddPersonFaceAsync(id, personId, Request.Files[0].InputStream);
            }
            catch (Exception ex)
            {
                ViewBag.Error = ex.Message;
                return View();
            }

            return RedirectToAction("Index", new { id = id });
        }
        
        [HttpGet]
        public async Task<ActionResult> Delete(string id, string personId)
        {
            var personGuid = Guid.Parse(Request["personId"]);
            await FaceClient.DeletePersonAsync(id, personGuid);
            return RedirectToAction("Index", new { id = id });
        }
    }
}

CognitiveServicesDemo/CognitiveServicesDemo/Areas/Faces/Views/People/AddFace.cshtml
@{
    ViewBag.Title = "AddFace";
}

<h2>Add face</h2>

@if (ViewBag.Error != null)
{
    <strong>@ViewBag.Error</strong>
}

<form method="post" enctype="multipart/form-data">
    Upload person face: <br />
    <input type="file" name="PersonFace" /><button type="submit">Send</button>
    <input type="hidden" name="id" value="@Request.RequestContext.RouteData.Values["id"]" />
    <input type="hidden" name="personId" value="@Request.RequestContext.RouteData.Values["personId"]" />
</form>

CognitiveServicesDemo/CognitiveServicesDemo/Areas/Faces/Views/People/Details.cshtml
@model Person
@{
    ViewBag.Title = "Details";
}

<h2>Person details</h2>

<div>
    <hr />
    <dl class="dl-horizontal">

        <dt>
            @Html.DisplayNameFor(model => model.PersonId)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.PersonId)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Name)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Name)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.UserData)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.UserData)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.PersistedFaceIds)
        </dt>
        <dd>
            @foreach (var id in Model.PersistedFaceIds)
            {
                @id <br />
            }
        </dd>
    </dl>
</div>
<p>
    @Html.ActionLink("Back to List", "Index", new { id = Request.RequestContext.RouteData.Values["id"] })
</p>

CognitiveServicesDemo/CognitiveServicesDemo/Areas/Faces/Views/People/Edit.cshtml
@model Person
@{
    var title = "Edit person";
    var isNew = (Model.PersonId == Guid.Empty);

    if (isNew)
    {
        title = "Add person";
    }
    ViewBag.Title = title;

}

<h2>@title</h2>

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <hr />
        @Html.ValidationSummary(false, null, new { @class = "text-danger" })

        <div class="form-group">
            @Html.LabelFor(model => model.Name, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.UserData, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.TextAreaFor(model => model.UserData, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.UserData, "", new { @class = "text-danger" })
            </div>
        </div>

        <input type="hidden" name="PersonGroupId" value="@ViewBag.PersonGroupId" />
        @Html.HiddenFor(m => m.PersonId);

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index", "People", new { id = ViewBag.PersonGroupId }, null)
</div>

CognitiveServicesDemo/CognitiveServicesDemo/Areas/Faces/Views/People/Index.cshtml
@model IEnumerable<Person>
@{
    ViewBag.Title = "People";
}

<h2>People</h2>

<p>
    @Html.ActionLink("Create New", "Create", new { id = ViewBag.PersonGroupId })
</p>

<table class="table">
    <tr>
        <th>ID</th>
        <th>Name</th>
        <th></th>
    </tr>

    @foreach (var item in Model)
            {
        <tr>
            <td>@item.PersonId</td>
            <td>@item.Name</td>
            <td>
                @Html.ActionLink("Details", "Details", new { id = ViewBag.PersonGroupId, personId = item.PersonId }) |
                @Html.ActionLink("Edit", "Edit", new { id = ViewBag.PersonGroupId, personId = item.PersonId }) |
                @Html.ActionLink("Add face", "AddFace", new { id = ViewBag.PersonGroupId, personId = item.PersonId }) |
                @Html.ActionLink("Delete", "Delete", new { id = ViewBag.PersonGroupId, personId = item.PersonId })
            </td>
        </tr>
    }
</table>