IdentifyProject/Controllers/SightedController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using IdentifyProject.Models;
using System.Data.Entity;
using System.IO;

namespace IdentifyProject.Controllers
{
    public class SightedController : Controller
    {
        // GET: Sighted
        public ActionResult Index()
        {
            return View();
        }
        public ActionResult ViewAll()
        {
            return View(GetAllSights());
        }

        IEnumerable<SightedDB> GetAllSights()
        {
            using (DBModel db = new DBModel())
            {
                return db.SightedDBs.ToList<SightedDB>();
            }

        }

        public ActionResult AddOrEdit(int id = 0)
        {
            SightedDB Sit = new SightedDB();
            if (id != 0)
            {
                using (DBModel db = new DBModel())
                {
                    Sit = db.SightedDBs.Where(x => x.SID == id).FirstOrDefault<SightedDB>();
                }
            }
            return View(Sit);
        }

        [HttpPost]
        public ActionResult AddOrEdit(SightedDB Sit)
        {
            try
            {
                if (Sit.ImageUpload != null)
                {
                    string fileName = Path.GetFileNameWithoutExtension(Sit.ImageUpload.FileName);
                    string extension = Path.GetExtension(Sit.ImageUpload.FileName);
                    fileName = fileName + DateTime.Now.ToString("yymmssfff") + extension;
                    Sit.ImagePath = "~/AppFiles/Images/" + fileName;
                    Sit.ImageUpload.SaveAs(Path.Combine(Server.MapPath("~/AppFiles/Images/"), fileName));
                }
                using (DBModel db = new DBModel())
                {
                    if (Sit.SID == 0)
                    {
                        db.SightedDBs.Add(Sit);
                        db.SaveChanges();
                    }
                    else
                    {
                        db.Entry(Sit).State = EntityState.Modified;
                        db.SaveChanges();

                    }
                }
                return Json(new { success = true, html = GlobalClass.RenderRazorViewToString(this, "ViewAll", GetAllSights()), message = "Submitted Successfully" }, JsonRequestBehavior.AllowGet);
            }
            catch (Exception ex)
            {

                return Json(new { success = false, message = ex.Message }, JsonRequestBehavior.AllowGet);
            }
        }

        public ActionResult Delete(int id)
        {
            try
            {
                using (DBModel db = new DBModel())
                {
                    SightedDB Sit = db.SightedDBs.Where(x => x.SID == id).FirstOrDefault<SightedDB>();
                    db.SightedDBs.Remove(Sit);
                    db.SaveChanges();
                }
                return Json(new { success = true, html = GlobalClass.RenderRazorViewToString(this, "ViewAll", GetAllSights()), message = "Deleted Successfully" }, JsonRequestBehavior.AllowGet);
            }
            catch (Exception ex)
            {
                return Json(new { success = false, message = ex.Message }, JsonRequestBehavior.AllowGet);
            }
        }
    }
}

IdentifyProject/Views/Sighted/AddOrEdit.cshtml
@model IdentifyProject.Models.SightedDB

@{
    ViewBag.Title = "AddOrEdit";
    Layout = null;
}


@using (Html.BeginForm("AddOrEdit", "Sighted", FormMethod.Post, new { enctype = "multipart/form-data", onSubmit = "return jQueryAjaxPost(this);", data_restUrl = Url.Action("AddOrEdit", "Sighted", new { id = 0 }) }))//data-resetUrl
{
    @Html.AntiForgeryToken()
    <div class="row">
        <div class="form-horizontal">
            
            <hr />
            @Html.ValidationSummary(true)
            @Html.HiddenFor(model => model.SID)
            @Html.HiddenFor(model => model.ImagePath)

            <div class="col-md-6">
                <div>
                    <p><i>PD: Physical Disability, MI: Mentally Ill</i></p>
                </div>


                <div class="form-group">
                    @Html.LabelFor(model => model.Name, htmlAttributes: new { @class = "control-label col-md-2" })
                    <div class="col-md-10">
                        @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control", @placeholder = "Name of person", required="required"} })
                        @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
                    </div>
                </div>

                <div class="form-group">
                    @Html.LabelFor(model => model.Age, htmlAttributes: new { @class = "control-label col-md-2" })
                    <div class="col-md-10">
                        @Html.EditorFor(model => model.Age, new { htmlAttributes = new { @class = "form-control", @placeholder = "approx age" , required = "required" } })
                        @Html.ValidationMessageFor(model => model.Age, "", new { @class = "text-danger" })
                    </div>
                </div>

                <div class="form-group">
                    @Html.LabelFor(model => model.Date, htmlAttributes: new { @class = "control-label col-md-2" })
                    <div class="col-md-10">
                        @Html.EditorFor(model => model.Date, new { htmlAttributes = new { @class = "form-control", @placeholder = "date of sight" , required = "required" } })
                        @Html.ValidationMessageFor(model => model.Date, "", new { @class = "text-danger" })
                    </div>
                </div>

                <div class="form-group">
                    @Html.LabelFor(model => model.CitizenName, htmlAttributes: new { @class = "control-label col-md-2" })
                    <div class="col-md-10">
                        @Html.EditorFor(model => model.CitizenName, new { htmlAttributes = new { @class = "form-control" , @placeholder = "citizen name", required = "required" } })
                        @Html.ValidationMessageFor(model => model.CitizenName, "", new { @class = "text-danger" })
                    </div>
                </div>

                <div class="form-group">
                    @Html.LabelFor(model => model.CitizenContact, htmlAttributes: new { @class = "control-label col-md-2" })
                    <div class="col-md-10">
                        @Html.EditorFor(model => model.CitizenContact, new { htmlAttributes = new { @class = "form-control", @placeholder = "contact", required = "required" } })
                        @Html.ValidationMessageFor(model => model.CitizenContact, "", new { @class = "text-danger" })
                    </div>
                </div>

                <div class="form-group">
                    @Html.LabelFor(model => model.Description, htmlAttributes: new { @class = "control-label col-md-2" })
                    <div class="col-md-10">
                        @Html.EditorFor(model => model.Description, new { htmlAttributes = new { @class = "form-control", @placeholder = "how/where the person was sighted , PD/MI?" , required = "required" } })
                        @Html.ValidationMessageFor(model => model.Description, "", new { @class = "text-danger" })
                    </div>
                </div>

                <div class="form-group">
                    @Html.LabelFor(model => model.Gender, htmlAttributes: new { @class = "control-label col-md-2" })
                    <div class="col-md-10">
                        @Html.EditorFor(model => model.Gender, new { htmlAttributes = new { @class = "form-control", required = "required" } })
                        @Html.ValidationMessageFor(model => model.Gender, "", new { @class = "text-danger" })
                    </div>
                </div>

                <div class="form-group">
                    @Html.LabelFor(model => model.City, htmlAttributes: new { @class = "control-label col-md-2" })
                    <div class="col-md-10">
                        @Html.EditorFor(model => model.City, new { htmlAttributes = new { @class = "form-control", @placeholder = "sighted city?", required = "required" } })
                        @Html.ValidationMessageFor(model => model.City, "", new { @class = "text-danger" })
                    </div>
                </div>

                <div class="form-group">
                    @Html.LabelFor(model => model.FIRNO, htmlAttributes: new { @class = "control-label col-md-2" })
                    <div class="col-md-10">
                        @Html.EditorFor(model => model.FIRNO, new { htmlAttributes = new { @class = "form-control", @placeholder = "type NIL if not filed" } })
                        @Html.ValidationMessageFor(model => model.FIRNO, "", new { @class = "text-danger" })
                    </div>
                </div>

                <div class="form-group">
                    @Html.LabelFor(model => model.Status, htmlAttributes: new { @class = "control-label col-md-2" })
                    <div class="col-md-10">
                        @Html.EditorFor(model => model.Status, new { htmlAttributes = new { @class = "form-control", @placeholder = "type NIL" } })
                        @Html.ValidationMessageFor(model => model.Status, "", new { @class = "text-danger" })
                    </div>
                </div>
                <div class="form-group">
                    <div class="col-md-offset-2 col-md-10">
                        <input type="submit" value="Submit" class="btn btn-default" />
                        @if (Model.SID != 0)
                        {
                            <a class="btn btn-success" onclick="refreshAddNewTab('@Url.Action("AddOrEdit","Sighted",new{id=0})',false)"><i class="fa fa-plus"></i> Add New</a>
                        }
                    </div>
                </div>
            </div>
            <div class="col-md-6">
                <div class="form-group">
                    @Html.LabelFor(model => model.ImagePath, htmlAttributes: new { @class = "control-label col-md-2" })
                    <div class="col-md-10">
                        <img src="@Url.Content(Model.ImagePath)" style="margin:10px" height="200" width="200" id="imagePreview" />
                        <input type="file" name="ImageUpload" accept="image/jpeg, image/png" onchange="ShowImagePreview(this,document.getElementById('imagePreview'))" />
                    </div>
                </div>
            </div>

        </div>
        </div>
        }

IdentifyProject/Views/Sighted/Index.cshtml
@{
    ViewBag.Title = "Index";
}

<h3>Sighted Details</h3>
<h5>Did you sighted someone whom you feel is lost? Fill in the details of the person whom you sighted.</h5><br />
<ul class="nav nav-tabs">
    <li class="active"><a data-toggle="tab" href="#firstTab">View All</a></li>
    <li><a data-toggle="tab" href="#secondTab">Add New</a></li>
</ul>
<div class="tab-content">
    <div id="firstTab" class="tab-pane fade in active">@Html.Action("ViewAll")</div>
    <div id="secondTab" class="tab-pane fade in ">@Html.Action("AddOrEdit")</div>

</div>

<link href="https://cdn.datatables.net/1.10.16/css/jquery.dataTables.min.css" rel="stylesheet" />
@section scripts{
    @Scripts.Render("~/bundles/jqueryval")

    <script src="https://cdn.datatables.net/1.10.16/js/jquery.dataTables.min.js"></script>


    <script>
        function activatejQueryTable() {
            $("#SightedTable").DataTable();
        }

        $(function () {
            activatejQueryTable();
        });

    </script>
    }

IdentifyProject/Views/Sighted/ViewAll.cshtml
@model IEnumerable<IdentifyProject.Models.SightedDB>

@{
    ViewBag.Title = "ViewAll";
    Layout = null;
}

<table class="table table-striped table-condensed" id="SightedTable">
    <thead>
        <tr>

            <th>
                @Html.DisplayNameFor(model => model.Name)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Age)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Date)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.CitizenName)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.CitizenContact)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Description)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Gender)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.City)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.FIRNO)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Status)
            </th>

            <th></th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model)
        {
            <tr>

                <td>
                    @Html.DisplayFor(modelItem => item.Name)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Age)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Date)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.CitizenName)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.CitizenContact)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Description)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Gender)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.City)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.FIRNO)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Status)
                </td>

                <td>
                    <a class="btn btn-primary btn-sm" onclick="Edit('@Url.Action("AddOrEdit", "Sighted", new { id=@item.SID})')"><i class="fa fa-pencil fa-lg"></i></a>
                    <a class="btn btn-danger btn-sm" onclick="Delete('@Url.Action("Delete", "Sighted", new { id=@item.SID})')"><i class="fa fa-trash fa-lg"></i></a>
                </td>
            </tr>
        }
    </tbody>
</table>